name: Integrity check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 8.2

    - name: Install composer deps
      run: |
        composer create-project squizlabs/php_codesniffer temp/php_codesniffer --no-progress

        # Install app deps
        composer install --no-interaction --prefer-dist

    # Check code checker and coding standards
    - name: Check coding standards
      run: |
        php temp/php_codesniffer/bin/phpcbf --standard=PSR12 src
        php temp/php_codesniffer/bin/phpcs --standard=PSR12 src

    - name: Check PHPStan rules
      run: composer phpstan
